import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_component/header";
import Footer from "./_component/footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-[100dvh]">
          <Header />
          {children}
          <Footer />
        </div>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
