import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_component/header";
import Footer from "./_component/footer";
import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex flex-col min-h-[100dvh]">
          <Header />
          {children}
          <Footer />
        </div>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
